// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Test$Uprolog from "./Test.bs.js";

var code = "test(X,Y).\ntest(aaa,bbb) :- test(aaa,bbb), test(aaa,bbb).\n";

var t = "test(X,Y).\n";

var executeCode = Test$Uprolog.text;

console.log(Test$Uprolog.text(code));

console.log(Test$Uprolog.text(t));

export {
  code ,
  t ,
  executeCode ,
  
}
/*  Not a pure module */
