// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Test$Uprolog from "./Test.bs.js";

var code = "parent(iwona,marcin).\nparent(iwona,tomek).\nsibling(X,Y) :- parent(Z, X), parent (Z, Y).\n?- siblings (W,M).";

var executeCode = Test$Uprolog.text;

console.log(Test$Uprolog.text(code));

var t = "test(X,Y).\n";

export {
  code ,
  t ,
  executeCode ,
  
}
/*  Not a pure module */
