// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Test$Uprolog = require("./Test.bs.js");

var code = "test(X,Y).\ntest(aaa,bbb) :- test(aaa,bbb), test(aaa,bbb).\n";

var t = "test(X,Y).\n";

var executeCode = Test$Uprolog.text;

console.log(Test$Uprolog.text(code));

console.log(Test$Uprolog.text(t));

exports.code = code;
exports.t = t;
exports.executeCode = executeCode;
/*  Not a pure module */
